[snowflake]
user="ahusain",
password="Murtaza@40401059",
account="ua60309.south-central-us.azure",
warehouse="RELMORA_COMPUTE",
database="RELMORA_DB",
schema="RELMORA_SCHEMA"

[postgres]
host     = "6vdjofao3jarzfssqxyteizsfq.skondys-et17731.southcentralus.azure.postgres.snowflake.app"
port     = 5432
dbname   = "postgres"
user     = "snowflake_admin"
password = "D6jHttcNb8T1zXa4dWMwHwQiuGhtD0m2mljCdgKIfMI4Y9vTwrRxuenEUNBCdBDd"